app = "waha-app2"
primary_region = "gru"

[build]
  dockerfile = "./Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  HOST = "0.0.0.0"


[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    restart_limit = 0
