app = "waha-app2"

[build]
  dockerfile = "./Dockerfile"

[env]
  WHATSAPP_HOOK_URL = "http://host.docker.internal:5678/webhook/webhook"
  WHATSAPP_DEFAULT_ENGINE = "GOWS"
  WHATSAPP_HOOK_EVENTS = "message"
  

[http_service]
  internal_port = 3000
  force_https = true
